// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./Card.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  RootPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "./_internal_primitives";
import Button, { ButtonContext } from "./Button";
import Image from "./Card.Image";

const styles = [
  {
    type: "default",
    layers: {
      "5uRiJyJcCR": {
        none: {
          text: "Title Text",
        },
      },
      "7JuX3xRCyj": {
        none: {
          text:
            "This is the text for the body of the card which goes across several lines, but tends to be limited to 3",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "darkMode",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      "4RSxsLvGGG": {
        none: {
          text: "Click Me",
          buttonType: "primary",
        },
      },
      Q8qN8UP5xA: {
        none: {
          text: "Or Me",
          buttonType: "secondary",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "darkMode",
    layers: {
      "4RSxsLvGGG": {},
      Q8qN8UP5xA: {},
    },
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "darkMode",
  },
];

export const CardContext = createContext(null);

function Card(_props) {
  const defaults = useContext(CardContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="3wEf8iCGS3"
      addSpacing={true}
      internal={{
        styles: styles,
        layerId: "3wEf8iCGS3",
        scope: "XAcKTXvug5",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.Image === undefined ? <Image key={"FGcrJL8exi"} /> : props.Image,
        <ContainerPrimitive
          className={"__visly_reset __visly_scope_XAcKTXvug5_BDVGLZ9gKW"}
          key={"BDVGLZ9gKW"}
          addSpacing={true}
        >
          <TextPrimitive
            className={"__visly_reset __visly_scope_XAcKTXvug5_5uRiJyJcCR"}
            key={"5uRiJyJcCR"}
            text={
              exists(props.titleText)
                ? props.titleText
                : getStyle("5uRiJyJcCR", "text")
            }
          />
          <TextPrimitive
            className={"__visly_reset __visly_scope_XAcKTXvug5_7JuX3xRCyj"}
            key={"7JuX3xRCyj"}
            text={
              exists(props.bodyText)
                ? props.bodyText
                : getStyle("7JuX3xRCyj", "text")
            }
          />
        </ContainerPrimitive>,
        <ContainerPrimitive
          className={"__visly_reset __visly_scope_XAcKTXvug5_FaFyjDGyP3"}
          key={"FaFyjDGyP3"}
          addSpacing={true}
        >
          {[
            props.PrimaryButton === undefined ? (
              <Button
                key={"4RSxsLvGGG"}
                {...getCompositeDefaultProps("4RSxsLvGGG")}
                className="__visly_reset __visly_scope_XAcKTXvug5_4RSxsLvGGG"
              />
            ) : (
              <ButtonContext.Provider
                key="4RSxsLvGGG-provider"
                value={{
                  key: "4RSxsLvGGG",
                  className:
                    "__visly_reset __visly_scope_XAcKTXvug5_4RSxsLvGGG",
                  ...getCompositeDefaultProps("4RSxsLvGGG"),
                }}
              >
                {props.PrimaryButton}
              </ButtonContext.Provider>
            ),
            props.SecondaryButton === undefined ? (
              <Button
                key={"Q8qN8UP5xA"}
                {...getCompositeDefaultProps("Q8qN8UP5xA")}
                className="__visly_reset __visly_scope_XAcKTXvug5_Q8qN8UP5xA"
              />
            ) : (
              <ButtonContext.Provider
                key="Q8qN8UP5xA-provider"
                value={{
                  key: "Q8qN8UP5xA",
                  className:
                    "__visly_reset __visly_scope_XAcKTXvug5_Q8qN8UP5xA",
                  ...getCompositeDefaultProps("Q8qN8UP5xA"),
                }}
              >
                {props.SecondaryButton}
              </ButtonContext.Provider>
            ),
          ]}
        </ContainerPrimitive>,
      ]}
    </RootPrimitive>
  );
}

Card.PrimaryButton = Button;
Card.SecondaryButton = Button;
Card.__variants = [
  {
    name: "darkMode",
    type: "variant",
  },
];

export default Card;
