// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./Card.Image.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, ImagePrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      "7Z2d9TJ6Ut": {
        none: {
          alternateText: "",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const ImageContext = createContext(null);

function Image(_props) {
  const defaults = useContext(ImageContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="7YyPW5fvWV"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "7YyPW5fvWV",
        scope: "Nz14feJndY",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ImagePrimitive
          className={"__visly_reset __visly_scope_Nz14feJndY_7Z2d9TJ6Ut"}
          key={"7Z2d9TJ6Ut"}
          src={
            exists(props.imageSrc1)
              ? props.imageSrc1
              : getStyle("7Z2d9TJ6Ut", "src")
          }
          alt={getStyle("7Z2d9TJ6Ut", "alternateText")}
        />
      )}
    </RootPrimitive>
  );
}

Image.__variants = [];

export default Image;
