// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./ProgressBar.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, ProgressFillPrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      fill: {
        none: {
          progress: 0.5,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const ProgressBarContext = createContext(null);

function ProgressBar(_props) {
  const defaults = useContext(ProgressBarContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "root",
        scope: "UDvVDQCGnZ",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ProgressFillPrimitive
          className={"__visly_reset __visly_scope_UDvVDQCGnZ_fill"}
          key={"fill"}
          value={
            exists(props.value) ? props.value : getStyle("fill", "progress")
          }
        />
      )}
    </RootPrimitive>
  );
}

ProgressBar.__variants = [];

export default ProgressBar;
